### ISSUE TITLE
Issue with PyInstaller and subprocessor

### ISSUE THREAD

**Issue by jjacobson95** [goodwright/nextflow.py#2]
Hi, I've been trying to use Pyinstaller on a python script that includes your nextflow wrapper. Everything works great when run normally, but when I use pyinstaller to turn this into an executable app, there are issues with subprocessor. I believe this has to do with a missing stdin that is required in this type of situation(?).
(stdin=subprocess.DEVNULL might do it)

Error Message:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "UI_mac.py", line 612, in run_nextflow
  File "nextflow/pipeline.py", line 69, in run
  File "nextflow/execution.py", line 25, in create_from_location
TypeError: 'NoneType' object is not subscriptable

**Comment by jjacobson95** [comment]
This was a versioning issue / bug with pyinstaller. Sorry for any confusion.
